# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: internal
generate:
  client: true
  models: true
output: openapi.gen.go
output-options:
  nullable-type: true
  user-templates:
    typedef.tmpl: |
      {{range .Types}}
        {{ if .Schema.Description }}{{ toGoComment .Schema.Description .TypeName  }}{{ else }}// {{.TypeName}} defines model for {{.JsonName}}.{{ end }}
        type {{.TypeName}} {{if .IsAlias }}={{end}} {{.Schema.TypeDecl}}

        {{$typeName := .TypeName}}
        {{range .Schema.Properties}}
          {{if or (eq .GoFieldName "Next") (eq .GoFieldName "Results")}}
            func (t {{$typeName}}) Get{{.GoFieldName}}() {{.GoTypeDef}} {
              return t.{{.GoFieldName}}
            }
          {{end}}
        {{end}}
      {{end}}
